// This is the memory map header file for 'decimation_filter'
// Generated by High Level Design Compiler for Intel(R) FPGAs Version 18.1 (Release Build #625) on Thu Jan 23 17:48:42 2025

// This file contains the address of each register in the design, with the block name, 
// read/write mode, and description in the block parameters as comments for each.

// Each section denotes one ModelIP/ModelBus block and is laid out as follows:
// <block name> : <description from block>
// <REGISTER_NAME>_BIT_WIDTH <bit width from block>
// <REGISTER_NAME>_FRAC_WIDTH <frac width from block>
// <REGISTER_NAME>_PRIVATE_SPACE <is the private register space box checked?>
// Then, for each addressable word of the block:
// <REGISTER_NAME>_LSB <LSB of word>
// <REGISTER_NAME>_MSB <MSB of word>
// <REGISTER_NAME>_WIDTH <width of word>
// <REGISTER_NAME> <word address in hex format> <read/write mode>

#define AVALON_BUS_WIDTH 16
#define AVALON_ADDRESS_WIDTH 11
// decimation_filter_FilterSystem_DecimatingFIR1 : FIR Coefficient Registers
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_BIT_WIDTH 16
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_FRAC_WIDTH 15
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_PRIVATE_SPACE false
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_LSB 0
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_MSB 15
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_WIDTH 16
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_STARTADDR 0x0 // Read/Write 
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR1_LENGTH 6 

// decimation_filter_FilterSystem_DecimatingFIR2 : FIR Coefficient Registers
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_BIT_WIDTH 16
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_FRAC_WIDTH 15
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_PRIVATE_SPACE false
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_LSB 0
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_MSB 15
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_WIDTH 16
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_STARTADDR 0x6 // Read/Write 
#define DECIMATION_FILTER_FILTERSYSTEM_DECIMATINGFIR2_LENGTH 14 

