// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Coefficient_Memory.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Coefficient_Memory
// Source Path: MDV_LMS/MDV LMS Algorithm/Filter/Coefficient Memory
// Hierarchy Level: 2
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Coefficient_Memory
          (clk,
           reset,
           enb,
           delayLine,
           coeffWrEnb,
           rdAddrs,
           coeffIn,
           rst,
           coeffOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] delayLine;  // sfix16_En13
  input   coeffWrEnb;
  input   [4:0] rdAddrs;  // ufix5
  input   signed [23:0] coeffIn;  // sfix24_En21
  input   rst;
  output  signed [23:0] coeffOut;  // sfix24_En21


  wire signed [23:0] out_re;  // sfix24_En21
  wire signed [23:0] out_im;  // sfix24_En21
  wire [4:0] Coeff_Controller_out2;  // ufix5
  wire Coeff_Controller_out3;
  reg signed [23:0] Delay2_out1_re;  // sfix24_En21
  reg signed [23:0] Delay2_out1_im;  // sfix24_En21
  reg [4:0] Delay_out1;  // ufix5
  reg  Delay1_out1;
  wire signed [23:0] Simple_Dual_Port_RAM1_out1_re;  // sfix24_En21
  wire signed [23:0] Simple_Dual_Port_RAM1_out1_im;  // sfix24_En21
  wire signed [23:0] y;  // sfix24_En21


  Coeff_Controller u_Coeff_Controller (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .din(coeffIn),  // sfix24_En21
                                       .rst(rst),
                                       .coeffWrenb(coeffWrEnb),
                                       .dout_re(out_re),  // sfix24_En21
                                       .dout_im(out_im),  // sfix24_En21
                                       .wrAddrs(Coeff_Controller_out2),  // ufix5
                                       .wrEnb(Coeff_Controller_out3)
                                       );

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1_re <= 24'sb000000000000000000000000;
        Delay2_out1_im <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_re <= out_re;
          Delay2_out1_im <= out_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 5'b00000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Coeff_Controller_out2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Coeff_Controller_out3;
        end
      end
    end

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_Simple_Dual_Port_RAM1 (.clk(clk),
                                                     .enb(enb),
                                                     .wr_din_re(Delay2_out1_re),
                                                     .wr_din_im(Delay2_out1_im),
                                                     .wr_addr(Delay_out1),
                                                     .wr_en(Delay1_out1),
                                                     .rd_addr(rdAddrs),
                                                     .dout_re(Simple_Dual_Port_RAM1_out1_re),
                                                     .dout_im(Simple_Dual_Port_RAM1_out1_im)
                                                     );

  MATLAB_Function1 u_MATLAB_Function1 (.u_re(Simple_Dual_Port_RAM1_out1_re),  // sfix24_En21
                                       .u_im(Simple_Dual_Port_RAM1_out1_im),  // sfix24_En21
                                       .u1(delayLine),  // sfix16_En13
                                       .y(y)  // sfix24_En21
                                       );

  assign coeffOut = y;

endmodule  // Coefficient_Memory

