// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Controller.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Controller
// Source Path: MDV_LMS/MDV LMS Algorithm/Filter/Coefficient Memory/Coeff Controller/Controller
// Hierarchy Level: 4
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Controller
          (clk,
           reset,
           enb,
           in,
           enb_1,
           rst,
           out_re,
           out_im,
           wrAdrs,
           enbWr);


  input   clk;
  input   reset;
  input   enb;
  input   signed [23:0] in;  // sfix24_En21
  input   enb_1;
  input   rst;
  output  signed [23:0] out_re;  // sfix24_En21
  output  signed [23:0] out_im;  // sfix24_En21
  output  [4:0] wrAdrs;  // ufix5
  output  enbWr;


  reg signed [23:0] out_re_1;  // sfix24_En21
  reg signed [23:0] out_im_1;  // sfix24_En21
  reg [4:0] wrAdrs_1;  // ufix5
  reg  enbWr_1;
  reg  state;
  reg [4:0] count;  // ufix5
  reg  state_next;
  reg [4:0] count_next;  // ufix5
  reg  cntHigh;


  always @(posedge clk or posedge reset)
    begin : Controller_1_process
      if (reset == 1'b1) begin
        state <= 1'b0;
        count <= 5'b00000;
      end
      else begin
        if (enb) begin
          state <= state_next;
          count <= count_next;
        end
      end
    end

  always @(count, enb_1, in, rst, state) begin
    state_next = state;
    count_next = count;
    // It provides input control signals to write updated filter coefficients to
    // the RAM.
    enbWr_1 = state && ( ! rst);
    cntHigh = (count == 5'b01111) && state;
    if (rst) begin
      state_next = 1'b0;
    end
    else if (enb_1) begin
      state_next = 1'b1;
    end
    else if (cntHigh) begin
      state_next = 1'b0;
    end
    // counter logic
    if ((cntHigh || enb_1) || rst) begin
      count_next = 5'b00000;
    end
    else if (state) begin
      count_next = count + 5'b00001;
    end
    out_re_1 = in;
    out_im_1 = 24'sb000000000000000000000000;
    wrAdrs_1 = count;
  end

  assign out_re = out_re_1;

  assign out_im = out_im_1;

  assign wrAdrs = wrAdrs_1;

  assign enbWr = enbWr_1;

endmodule  // Controller

