// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Data_Conversion.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Conversion
// Source Path: MDV_LMS/MDV LMS Algorithm/Coefficient Update/Multiplier1/Data Conversion
// Hierarchy Level: 3
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Conversion
          (u,
           u1,
           y);


  input   signed [40:0] u;  // sfix41_En34
  input   signed [22:0] u1;  // sfix23_En16
  output  signed [22:0] y;  // sfix23_En21




  //#Codegen
  // The wordlength and fractional length adjusted based on simulation
  assign y = u[35:13];

endmodule  // Data_Conversion

