// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Data_Type_Conversion.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Type_Conversion
// Source Path: MDV_LMS/MDV LMS Algorithm/Data Type  Conversion
// Hierarchy Level: 1
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Type_Conversion
          (u1,
           y);


  input   signed [39:0] u1;  // sfix40_En34
  output  signed [23:0] y;  // sfix24_En21


  wire signed [23:0] Data_Type_Conversion_Inherited_out1;  // sfix24_En21


  Data_Type_Conversion_Inherited u_Data_Type_Conversion_Inherited (.u(u1),  // sfix40_En34
                                                                   .y(Data_Type_Conversion_Inherited_out1)  // sfix24_En21
                                                                   );

  assign y = Data_Type_Conversion_Inherited_out1;

endmodule  // Data_Type_Conversion

