// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Data_Control.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Control
// Source Path: MDV_LMS/MDV LMS Algorithm/Data Control
// Hierarchy Level: 1
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Control
          (clk,
           reset,
           enb,
           reset_1,
           validIn,
           adapt,
           adaptOut,
           validOut,
           readyOut);


  input   clk;
  input   reset;
  input   enb;
  input   reset_1;
  input   validIn;
  input   adapt;
  output  adaptOut;
  output  validOut;
  output  readyOut;




  Input_Control u_Input_Control (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .reset_1(reset_1),
                                 .validIn(validIn),
                                 .adapt(adapt),
                                 .adaptOut(adaptOut),
                                 .validOut(validOut),
                                 .readyOut(readyOut)
                                 );

endmodule  // Data_Control

