// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Data_Conversion_block.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Conversion_block
// Source Path: MDV_LMS/MDV LMS Algorithm/Coefficient Update/Multiplier2/Data Conversion
// Hierarchy Level: 3
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Conversion_block
          (u,
           const_rsvd);


  input   signed [15:0] u;  // sfix16_En13
  output  signed [16:0] const_rsvd;  // sfix17_En13




  //#Codegen
  // The wordlength and fractional length adjusted based on simulation
  assign const_rsvd = {u[15], u};

endmodule  // Data_Conversion_block

