// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\MATLAB_Function1.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function1
// Source Path: MDV_LMS/MDV LMS Algorithm/Filter/Coefficient Memory/MATLAB Function1
// Hierarchy Level: 3
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function1
          (u_re,
           u_im,
           u1,
           y);


  input   signed [23:0] u_re;  // sfix24_En21
  input   signed [23:0] u_im;  // sfix24_En21
  input   signed [15:0] u1;  // sfix16_En13
  output  signed [23:0] y;  // sfix24_En21




  assign y = u_re;

endmodule  // MATLAB_Function1

