// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Multiplier_block1.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Multiplier_block1
// Source Path: MDV_LMS/MDV LMS Algorithm/Filter/Multiplier
// Hierarchy Level: 2
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Multiplier_block1
          (clk,
           enb,
           in1,
           in2,
           mulOut);


  input   clk;
  input   enb;
  input   signed [15:0] in1;  // sfix16_En13
  input   signed [23:0] in2;  // sfix24_En21
  output  signed [39:0] mulOut;  // sfix40_En34


  wire signed [39:0] out;  // sfix40_En34


  multiplier_block u_multiplier (.clk(clk),
                                 .enb(enb),
                                 .in1(in1),  // sfix16_En13
                                 .in2(in2),  // sfix24_En21
                                 .out(out)  // sfix40_En34
                                 );

  assign mulOut = out;

endmodule  // Multiplier_block1

