// -------------------------------------------------------------
// 
// File Name: C:\Users\dell\Desktop\xilinx_DLP\adaptive\mdv_lms_hdl_coder\MDV_LMS\Reset_Data.v
// Created: 2025-04-30 11:34:40
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Reset_Data
// Source Path: MDV_LMS/MDV LMS Algorithm/Filter/Reset Data
// Hierarchy Level: 2
// Model version: 8.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Reset_Data
          (data,
           coeff,
           dataRst,
           coeffRst,
           delayLine,
           oldCoeff);


  input   signed [15:0] data;  // sfix16_En13
  input   signed [23:0] coeff;  // sfix24_En21
  input   dataRst;
  input   coeffRst;
  output  signed [15:0] delayLine;  // sfix16_En13
  output  signed [23:0] oldCoeff;  // sfix24_En21


  reg signed [15:0] delayLine_1;  // sfix16_En13
  reg signed [23:0] oldCoeff_1;  // sfix24_En21


  always @(coeff, coeffRst, data, dataRst) begin
    // Resets the input and coefficient memory.
    if (dataRst) begin
      // cast data type based on inputs
      delayLine_1 = 16'sb0000000000000000;
    end
    else begin
      delayLine_1 = data;
    end
    if (coeffRst) begin
      // cast data type based on inputs
      oldCoeff_1 = 24'sb000000000000000000000000;
    end
    else begin
      oldCoeff_1 = coeff;
    end
  end

  assign delayLine = delayLine_1;

  assign oldCoeff = oldCoeff_1;

endmodule  // Reset_Data

