# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_adaptive_vivado.srcs/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/decimation_1ch_d128_20_fir_compiler_v7_2_i6.xci
# IP: The module: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_1ch_d128_20.gen/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_1ch_d128_20.gen/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/decimation_1ch_d128_20_fir_compiler_v7_2_i6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_adaptive_vivado.srcs/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/decimation_1ch_d128_20_fir_compiler_v7_2_i6.xci
# IP: The module: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_1ch_d128_20.gen/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dell/Desktop/xilinx_DLP/decimation_adaptive_vivado/decimation_1ch_d128_20.gen/sources_1/ip/decimation_1ch_d128_20_fir_compiler_v7_2_i6/decimation_1ch_d128_20_fir_compiler_v7_2_i6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimation_1ch_d128_20_fir_compiler_v7_2_i6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
